version: '1'
services:
  frontend:
    container_name: quiz-converter-frontend
    depends_on:
      - backend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 80:3000
  backend:
    container_name: quiz-converter-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8000:8000
